package com.example.sportsorganizer.data.local.entities

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a user of the application (Organizer).
 *
 * This data class maps to the `users` table in the Supabase database.
 * It is used for authentication and associating competitions with organizers.
 *
 * @property id The unique identifier for the user (generated by Supabase).
 * @property firstName The user's first name.
 * @property lastName The user's last name.
 * @property username The user's chosen username for login.
 * @property passwordHash The hashed password for security.
 */
@Serializable
data class User(
    val id: Long = 0, // Supabase will generate this
    @SerialName("first_name") val firstName: String?,
    @SerialName("last_name") val lastName: String?,
    val username: String,
    @SerialName("password_hash") val passwordHash: String
)
